version: '3.9'

services:
  
  backend:
    build: ./test
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./test/:/usr/src/lomax/
    ports:
      - 8000:8000
    env_file:
      - ./conf.env
    depends_on:
      - db
    container_name: django_backend

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lomax
    container_name: postgres_db

volumes:
  postgres_data:
