version: '3.9'

services:
  
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/lomex/
    ports:
      - 8000:8000
    env_file:
      - ./conf.env
    depends_on:
      - db
    container_name: django_backend

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lomex
    container_name: postgres_db
  vue:
    build: ./frontend
    command: npm run serve
    volumes:
      - ./frontend/:/usr/src/lomex/
    ports:
      - "8080:8080"
    depends_on:
      - backend
    container_name: vue_frontend

volumes:
  postgres_data:
